language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3
      sudo: required

env:
  global:
    - CI_WORK=`pwd`

addons:
  apt:
    packages:
      - qtbase5-dev
      - qt5-default
      - qt5-qmake
      - qttools5-dev-tools
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - libsqlite3-dev
      - gdb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; brew link --force qt; fi

install:
  - qmake -v
  - ./configure --prefix=/usr/local
  - make -j4 -C src
  - sudo make -C src install
  - make -j4 -C tools
  - sudo make -C tools install
  - treefrog -v

before_script:
  - cd $CI_WORK
  - cd tools/tmake/test
  - qmake tmaketest.pro
  - make

script:
  - cd $CI_WORK
  - ./src/test/testall.sh
  - cd tools/tmake/test
  - ./tmaketest
