language: cpp

env:
  global:
    - CI_WORK=`pwd`

install:
  - g++ --version
  - qmake -v
  - ./configure
  - make  -j4 -C src
  - sudo make -C src install
  - make  -j4 -C tools
  - sudo make -C tools install
  - treefrog -v

before_script:
  - cd $CI_WORK
  - cd tools/tmake/test
  - qmake tmaketest.pro
  - make

script:
  - cd $CI_WORK
  - ./src/test/testall.sh
  - cd tools/tmake/test
  - ./tmaketest
