#
# appveyor.yml
#
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Skipping commits affecting specific files (GitHub only).
skip_commits:
  files:
    - docs/*
    - '**/*.html'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      INIT_BAT: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      QT_PATH: C:\Qt\5.12.2\msvc2015_64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      INIT_BAT: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      QT_PATH: C:\Qt\5.12.2\msvc2017_64

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf false
  - "%INIT_BAT%" amd64
  - set PATH=%QT_PATH%\bin;C:\tools\vcpkg\installed\x86-windows\tools;C:\tools\vcpkg\installed\x86-windows\tools\curl;%PATH%

install:
  - vcpkg install --recurse sqlite3[tool] curl[tool]

# to disable automatic builds
build: off

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: echo %PATH%
  - cmd: configure.bat --enable-debug
  - cmd: cd src
  - cmd: nmake install
  - cmd: cd ..\tools
  - cmd: nmake install
  - cmd: cd ..
  - cmd: configure.bat
  - cmd: cd src
  - cmd: nmake install
  - cmd: cd ..\tools
  - cmd: nmake install
  - cmd: cd test
  - cmd: releasetest\releasetest.bat
