version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - run: apt-get update -qq; apt install -y --no-install-recommends gcc g++ make cmake qtbase5-dev qt5-default qt5-qmake qttools5-dev-tools qtdeclarative5-dev qtdeclarative5-dev-tools libqt5sql5 libqt5sql5-sqlite libsqlite3-dev libmongoc-dev libbson-dev gdb ruby ruby-dev ruby-all-dev gem
      - run: qmake -v
      - run: ./configure --prefix=/usr/local
      - run: make -j4 -C src && make -C src install && make -j4 -C tools && make -C tools install
      - run: treefrog -v

